"""
Property-based tests for recommendation system.
"""
import sys
sys.path.append('.')

import pytest
from hypothesis import given, settings, strategies as st
from src.data_generator import DataGenerator
import pandas as pd
import numpy as np


# Configure Hypothesis
settings.register_profile("dev", max_examples=100, deadline=None)
settings.load_profile("dev")


# Feature: cart-addon-recommendation-system, Property 1: Generated user profiles are complete and valid
@given(
    n_users=st.integers(min_value=10, max_value=500),
    cities=st.lists(st.sampled_from(['Mumbai', 'Delhi', 'Bangalore']), min_size=1, max_size=3)
)
@settings(max_examples=100)
def test_property_1_user_profiles_complete_and_valid(n_users, cities):
    """
    Property 1: For any user generated by the Data_Generator, all required fields
    should be present and values should be within valid ranges.
    
    Validates: Requirements 1.1
    """
    generator = DataGenerator()
    users_df = generator.generate_users(n_users=n_users, cities=cities)
    
    # Check all users have required fields
    required_fields = [
        'user_id', 'city', 'segment', 'order_count_30d', 'order_count_90d',
        'avg_order_value', 'days_since_last_order', 'preferred_cuisines'
    ]
    
    for field in required_fields:
        assert field in users_df.columns, f"Missing required field: {field}"
        assert users_df[field].notna().all(), f"Field {field} has null values"
    
    # Check value ranges
    assert (users_df['order_count_30d'] >= 0).all(), "order_count_30d must be non-negative"
    assert (users_df['order_count_90d'] >= users_df['order_count_30d']).all(), "90d count must be >= 30d count"
    assert (users_df['avg_order_value'] >= 0).all(), "avg_order_value must be non-negative"
    assert users_df['segment'].isin(['budget', 'premium', 'frequent']).all(), "Invalid segment values"
    assert users_df['city'].isin(cities).all(), "Invalid city values"


# Feature: cart-addon-recommendation-system, Property 5: Cold-start scenarios are represented
@given(
    n_users=st.integers(min_value=100, max_value=1000)
)
@settings(max_examples=50)
def test_property_5_cold_start_users_present(n_users):
    """
    Property 5: For any generated dataset, at least 15% of users should have
    fewer than 5 orders (cold-start scenario).
    
    Validates: Requirements 1.5
    """
    generator = DataGenerator()
    users_df = generator.generate_users(n_users=n_users)
    
    cold_start_users = users_df[users_df['order_count_90d'] < 5]
    cold_start_ratio = len(cold_start_users) / len(users_df)
    
    # Allow some tolerance (10-20% range)
    assert 0.10 <= cold_start_ratio <= 0.25, \
        f"Cold-start ratio {cold_start_ratio:.2%} outside expected range [10%, 25%]"


# Feature: cart-addon-recommendation-system, Property 8: Temporal data splits prevent leakage
@given(
    n_sessions=st.integers(min_value=100, max_value=500),
    test_split_ratio=st.floats(min_value=0.1, max_value=0.3)
)
@settings(max_examples=50)
def test_property_8_temporal_split_no_leakage(n_sessions, test_split_ratio):
    """
    Property 8: For any train-test split, max(train_timestamps) < min(test_timestamps).
    
    Validates: Requirements 1.9, 4.5, 5.7
    """
    generator = DataGenerator()
    
    # Generate minimal data for testing
    users = generator.generate_users(50, ['Mumbai'])
    restaurants = generator.generate_restaurants(20, ['Mumbai'])
    items = generator.generate_menu_items(restaurants)
    
    sessions = generator.generate_cart_sessions(
        users=users,
        restaurants=restaurants,
        items=items,
        n_sessions=n_sessions,
        start_date='2024-01-01',
        end_date='2024-02-01'
    )
    
    if len(sessions) < 10:
        return  # Skip if too few sessions generated
    
    # Create temporal split
    train_df, val_df, test_df = generator.create_temporal_split(
        sessions, test_ratio=test_split_ratio
    )
    
    # Verify no leakage
    max_train_time = pd.to_datetime(train_df['timestamp']).max()
    min_test_time = pd.to_datetime(test_df['timestamp']).min()
    
    assert max_train_time < min_test_time, \
        "Temporal leakage detected: train data overlaps with test data"


# Feature: cart-addon-recommendation-system, Property 19: Recommendations exclude cart items
@given(
    cart_size=st.integers(min_value=1, max_value=5)
)
@settings(max_examples=100)
def test_property_19_recommendations_exclude_cart_items(cart_size):
    """
    Property 19: For any cart and set of recommendations, no recommended item
    should already be present in the cart.
    
    Validates: Requirements 7.2
    """
    from src.recommendation_engine import RecommendationEngine
    
    # Create mock cart items
    cart_items = [
        {'item_id': f'item_{i}', 'name': f'Item {i}', 'price': 100}
        for i in range(cart_size)
    ]
    
    # Try to get recommendations (may fail if model not trained, that's ok)
    try:
        engine = RecommendationEngine()
        recommendations = engine.get_recommendations(
            user_id='user_0',
            restaurant_id='rest_0',
            cart_items=cart_items,
            top_n=10
        )
        
        # Verify no cart items in recommendations
        cart_item_ids = {item['item_id'] for item in cart_items}
        recommended_item_ids = {item['item_id'] for item in recommendations}
        
        assert cart_item_ids.isdisjoint(recommended_item_ids), \
            "Recommendations contain items already in cart"
    except Exception as e:
        # If engine not initialized (model not trained), skip test
        pytest.skip(f"Engine not available: {e}")


# Feature: cart-addon-recommendation-system, Property 21: Recommendations show diversity
@given(
    top_n=st.integers(min_value=5, max_value=10)
)
@settings(max_examples=50)
def test_property_21_recommendations_show_diversity(top_n):
    """
    Property 21: For any set of top-N recommendations, the items should span
    multiple categories, not all from the same category.
    
    Validates: Requirements 7.5
    """
    from src.recommendation_engine import RecommendationEngine
    
    cart_items = [{'item_id': 'item_0', 'name': 'Pizza', 'price': 300}]
    
    try:
        engine = RecommendationEngine()
        recommendations = engine.get_recommendations(
            user_id='user_0',
            restaurant_id='rest_0',
            cart_items=cart_items,
            top_n=top_n
        )
        
        if len(recommendations) >= 3:
            # Check category diversity
            categories = [item.get('category', 'unknown') for item in recommendations]
            unique_categories = len(set(categories))
            
            # Should have at least 2 different categories if we have 3+ recommendations
            assert unique_categories >= 2, \
                f"Recommendations lack diversity: only {unique_categories} category"
    except Exception as e:
        pytest.skip(f"Engine not available: {e}")


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
